config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  get 'static_pages/calories'
  devise_for :users
  get '/search' => 'calos#search', :as => 'search_calo'
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :calos,          only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calo.rb
class Calo < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
#  validates :ncal && :qcal, numericality: true
#  validates :ncal || :qcal, presence: true
  validates :ncal, presence: true, unless: ->(calo){calo.qcal.present?}
  validates :coment, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :calos, dependent: :destroy
  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end
  
end

app/controllers/calos_controller.rb
class CalosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @calo = current_user.calos.build(calo_params)
    if  @calo.qcal.nil?
      @calo.qcal=0
    elsif @calo.ncal.nil?
      @calo.ncal=0
    end
    if @calo.save
      flash[:success] = "Se ha registrado tu uso calorias!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
    
  def search
    @string=params[:search]
   if params[:search].blank?  
     redirect_to(root_path, alert: "Empty field!") and return  
   else  
    @parameter = params[:search].downcase  
    @results = Calo.all.where("lower(coment) LIKE :search", search: "#{@parameter}")  
   end
  end


  def destroy
    @cal= current_user.calos.find_by(id: params[:id])
    @cal.destroy
    flash[:success] = "El registro fue eliminado!"
    redirect_to request.referrer || root_url
  end
  private

    def calo_params
      params.require(:calo).permit(:coment, :ncal, :qcal)
    end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @calo = current_user.calos.build if user_signed_in?
  end

  def calories
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [ :destroy]
    
  def index
    @users = User.all.page(params[:page])
  end

 def show    
      @member=User.find(params[:id])
      @calos = @member.calos.page(params[:page])
      @ddata=@member.calos.first(2)
      max=@member.calos.count - 1
      (2..max).each do |i|
        if @member.calos[i].created_at > Time.now - 60*60*24*30
          @ddata << @member.calos[i]
        end
      end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caloria_helper.rb
module CaloriaHelper
end

app/helpers/calos_helper.rb
module CalosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calos/_calo.html.erb
<li id="calo-<%= calo.id %>"
  <span class="user"><%= link_to calo.user.name, calo.user %></span> 
  <span class="content"> 
  <%if calo.ncal.present?%>
  consumio
  <%= calo.ncal %></span>
  <%else%>
  gasto
  <%= calo.qcal %></span>
  <%end%>calorias
  <%if calo.coment.present?%>
  con la accion "
  <span class="content"><%= calo.coment %></span> "
  <%end%>
  <span class="timestamp">
    Publicado <%= time_ago_in_words(calo.created_at) %> ago.
  </span>
   <%if current_user==@member%>
   <%= link_to "Eliminar", calo, method: :delete,
                                       data: { confirm: "Esta Seguro?" } %>
   <%end%>
</li>

app/views/calos/search.html.erb
<h3>Search Result</h3>  

    <% @results.each do |result| %>  
    <%= User.find(result.user_id).name %> 
<%if result.ncal!=0%>
  consumio
  <%= result.ncal %></span>
  <%else%>
  gasto
  <%= result.qcal %></span>
  <%end%>calorias
  
  <%if result.coment.present?%>
  con la accion "
  <span class="content"><%= result.coment %></span> "
  <%end%>
  <span class="timestamp">
    Publicado <%= time_ago_in_words(result.created_at) %> ago.
  </span>
    <% end %>

app/views/layouts/_header.html.erb
<section class='hero is-primary'>
  <body>
     <% if notice %>
       <p class="alert alert-success"><%= notice %></p>
     <% end %>
     <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
     <% end %>
  
<%= form_tag(search_calo_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:coment => nil%>  
    </div>  
  </div>  
<% end %>
<nav class="navbar" role="navigation" aria-label="main navigation">
      <%= render 'layouts/header' %>
        <div id="navbarBasicExample" class="navbar-menu">
   <div class="navbar-start">
    <% if user_signed_in? %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <a class="navbar-item">
       <%= link_to "Inicio", root_path, :class => 'navbar-link'  %>
      </a>
      
      <a class="navbar-item">
      <%= link_to "Mi Perfil", current_user, :class => 'navbar-link'  %>
      </a>
      
      <a class="navbar-item">
      <%= link_to "Usuarios", users_index_path, :class => 'navbar-link'  %>
      </a>
      
      <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-dropdown">
          <a class="navbar-item">
           <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %>
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
             <%= link_to "Cerrar Cesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
          </a>
        </div>
      </div>
      <% else %>
      
      <a class="navbar-item">
       <%= link_to "Pagina Principal", root_path, :class => 'navbar-link'  %>
      </a> 
      <a class="navbar-item">
       <%= link_to "Registrate!", new_user_registration_path, :class => 'navbar-link'  %>
      </a> 
      <a class="navbar-item">
       <%= link_to "Iniciar cesion", new_user_session_path, :class => 'navbar-link'  %> 
      </a> 
      <% end %>
    </div>
</section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-7">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Calorias</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
<section class='hero is-primary'>
  <body>
     <% if notice %>
       <p class="alert alert-success"><%= notice %></p>
     <% end %>
     <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
     <% end %>
  
<%= form_tag(search_calo_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:coment => nil%>  
    </div>  
  </div>  
<% end %>
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
 <% if user_signed_in? %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <%= link_to "Inicio", root_path, :class => 'navbar-link'  %> 
  <%= link_to "Mi Perfil", current_user, :class => 'navbar-link'  %> 
  <%= link_to "Usuarios", users_index_path, :class => 'navbar-link'  %> 
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Cerrar Cesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
<% else %>
  <%= link_to "Pagina Principal", root_path, :class => 'navbar-link'  %> 
  <%= link_to "Registrate!", new_user_registration_path, :class => 'navbar-link'  %> 
  <%= link_to "Iniciar cesion", new_user_session_path, :class => 'navbar-link'  %>  
<% end %>
    </a>
  </div>
</section>
    <%= yield %>
  </body>
</html>

app/views/shared/_calo_form.html.erb
<%= form_with(model: @calo, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
  <strong> <%= f.label "Numero de calorias Consumidas"%><br /></strong>
    <%= f.number_field :ncal, placeholder: "Registra tu consumo de calorias..." %>
  </div>

  <div class="field">
   <strong> <%= f.label "Numero de calorias Gastadas"%></strong><br />
    <%= f.number_field :qcal, placeholder: "Registra tu quema de calorias...", :input_html => { :value => 0} %>
  </div>
  
  <div class="field">
   <strong>  <%= f.label "Como quemaste o consumiste tus calorias?"%><br /></strong>
    <%= f.text_area :coment, placeholder: "Como quemaste o consumiste tus calorias?" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1 class=title><%= current_user.name %></h1>
<span><%= link_to "Mira mi perfil", current_user %></span>
<span><%= pluralize(current_user.calos.count, "Registros") %></span><br />

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  
<% if user_signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="calo_form">
        <%= render 'shared/calo_form' %>
      </section>
    </aside>
  </div>
<% else %>

  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        Manten Un Registro De Tus Calorias
      </h1>
      <p class="subtitle">
        Metabolismo <strong>En Rails</strong>!
      </p>
    </div>
  </section>
  </body>
<%end%>
</html>

app/views/users/_user.html.erb
        <h1 class="title">
        <span><%= link_to user.name, user %></span>
        </h1>
      <p class="subtitle">
        <%=  user.email %>
      </p>

app/views/users/index.html.erb
<% provide(:title, 'Lista de Usuarios') %>

      <h1 class="title is-large">
        Lista de Usuarios
      </h1>

 <section class="section">
    <div class="container">
      <ol class="users">
   <%= render @users %>
      <%= paginate @users%>
      </ol>
    </div>
  </section>

app/views/users/show.html.erb
<% provide(:title, 'perfil') %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1 class='title'>
        <%= @member.name %> 
      </h1>
      <h4>
        <%= @member.email %> 
      </h4>      
      
      <%= line_chart [{name: "calorias gastadas", data: @ddata.map{|calo| [calo.created_at, calo.qcal] }},
{name: "calorias consumidas", data: @ddata.map{|calo| [calo.created_at, calo.ncal] }}]%>

        <div class="col-md-8">
          <% if @member.calos.any? %> <br />
            <strong>Calorias registradas (<%= @member.calos.count %>)</strong>
            <ol class="calos">
              <%= render @calos %>
            </ol>
          <% end %>
          <%= paginate @calos%>
        </div>
    </section>
  </aside>
</div>
 